package com.example.demo.dao;

import com.example.demo.entity.ShopHistoryorderEntity;
import com.example.demo.entity.ShopHistoryorderEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopHistoryorderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_historyorder_entity
     *
     * @mbggenerated
     */
    int countByExample(ShopHistoryorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_historyorder_entity
     *
     * @mbggenerated
     */
    int deleteByExample(ShopHistoryorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_historyorder_entity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_historyorder_entity
     *
     * @mbggenerated
     */
    int insert(ShopHistoryorderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_historyorder_entity
     *
     * @mbggenerated
     */
    int insertSelective(ShopHistoryorderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_historyorder_entity
     *
     * @mbggenerated
     */
    List<ShopHistoryorderEntity> selectByExample(ShopHistoryorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_historyorder_entity
     *
     * @mbggenerated
     */
    ShopHistoryorderEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_historyorder_entity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShopHistoryorderEntity record, @Param("example") ShopHistoryorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_historyorder_entity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShopHistoryorderEntity record, @Param("example") ShopHistoryorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_historyorder_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShopHistoryorderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_historyorder_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShopHistoryorderEntity record);
}