package com.example.demo.dao;

import com.example.demo.entity.ShopEntity;
import com.example.demo.entity.ShopEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_entity
     *
     * @mbggenerated
     */
    int countByExample(ShopEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_entity
     *
     * @mbggenerated
     */
    int deleteByExample(ShopEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_entity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_entity
     *
     * @mbggenerated
     */
    int insert(ShopEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_entity
     *
     * @mbggenerated
     */
    int insertSelective(ShopEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_entity
     *
     * @mbggenerated
     */
    List<ShopEntity> selectByExample(ShopEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_entity
     *
     * @mbggenerated
     */
    ShopEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_entity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShopEntity record, @Param("example") ShopEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_entity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShopEntity record, @Param("example") ShopEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShopEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShopEntity record);
}