package com.example.demo.dao;

import com.example.demo.entity.ShopDishesEntity;
import com.example.demo.entity.ShopDishesEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopDishesEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_dishes_entity
     *
     * @mbggenerated
     */
    int countByExample(ShopDishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_dishes_entity
     *
     * @mbggenerated
     */
    int deleteByExample(ShopDishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_dishes_entity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_dishes_entity
     *
     * @mbggenerated
     */
    int insert(ShopDishesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_dishes_entity
     *
     * @mbggenerated
     */
    int insertSelective(ShopDishesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_dishes_entity
     *
     * @mbggenerated
     */
    List<ShopDishesEntity> selectByExample(ShopDishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_dishes_entity
     *
     * @mbggenerated
     */
    ShopDishesEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_dishes_entity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShopDishesEntity record, @Param("example") ShopDishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_dishes_entity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShopDishesEntity record, @Param("example") ShopDishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_dishes_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShopDishesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_dishes_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShopDishesEntity record);
}