package com.example.demo.dao;

import com.example.demo.entity.UserHistoryorderEntity;
import com.example.demo.entity.UserHistoryorderEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserHistoryorderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historyorder_entity
     *
     * @mbggenerated
     */
    int countByExample(UserHistoryorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historyorder_entity
     *
     * @mbggenerated
     */
    int deleteByExample(UserHistoryorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historyorder_entity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historyorder_entity
     *
     * @mbggenerated
     */
    int insert(UserHistoryorderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historyorder_entity
     *
     * @mbggenerated
     */
    int insertSelective(UserHistoryorderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historyorder_entity
     *
     * @mbggenerated
     */
    List<UserHistoryorderEntity> selectByExample(UserHistoryorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historyorder_entity
     *
     * @mbggenerated
     */
    UserHistoryorderEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historyorder_entity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserHistoryorderEntity record, @Param("example") UserHistoryorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historyorder_entity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserHistoryorderEntity record, @Param("example") UserHistoryorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historyorder_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserHistoryorderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historyorder_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserHistoryorderEntity record);
}