package com.example.demo.entity;

import java.util.Date;

public class ShopEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_entity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_entity.shopname
     *
     * @mbggenerated
     */
    private String shopname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_entity.hostname
     *
     * @mbggenerated
     */
    private String hostname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_entity.shoptopic
     *
     * @mbggenerated
     */
    private String shoptopic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_entity.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_entity.starttime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_entity.endtime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_entity.credit
     *
     * @mbggenerated
     */
    private Float credit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_entity.id
     *
     * @return the value of shop_entity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_entity.id
     *
     * @param id the value for shop_entity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_entity.shopname
     *
     * @return the value of shop_entity.shopname
     *
     * @mbggenerated
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_entity.shopname
     *
     * @param shopname the value for shop_entity.shopname
     *
     * @mbggenerated
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_entity.hostname
     *
     * @return the value of shop_entity.hostname
     *
     * @mbggenerated
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_entity.hostname
     *
     * @param hostname the value for shop_entity.hostname
     *
     * @mbggenerated
     */
    public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_entity.shoptopic
     *
     * @return the value of shop_entity.shoptopic
     *
     * @mbggenerated
     */
    public String getShoptopic() {
        return shoptopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_entity.shoptopic
     *
     * @param shoptopic the value for shop_entity.shoptopic
     *
     * @mbggenerated
     */
    public void setShoptopic(String shoptopic) {
        this.shoptopic = shoptopic == null ? null : shoptopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_entity.address
     *
     * @return the value of shop_entity.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_entity.address
     *
     * @param address the value for shop_entity.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_entity.starttime
     *
     * @return the value of shop_entity.starttime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_entity.starttime
     *
     * @param starttime the value for shop_entity.starttime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_entity.endtime
     *
     * @return the value of shop_entity.endtime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_entity.endtime
     *
     * @param endtime the value for shop_entity.endtime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_entity.credit
     *
     * @return the value of shop_entity.credit
     *
     * @mbggenerated
     */
    public Float getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_entity.credit
     *
     * @param credit the value for shop_entity.credit
     *
     * @mbggenerated
     */
    public void setCredit(Float credit) {
        this.credit = credit;
    }
}