package com.example.demo.entity;

public class ShopDishesEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_dishes_entity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_dishes_entity.shopname
     *
     * @mbggenerated
     */
    private String shopname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_dishes_entity.shopdishes
     *
     * @mbggenerated
     */
    private String shopdishes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_dishes_entity.price
     *
     * @mbggenerated
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_dishes_entity.ingredient
     *
     * @mbggenerated
     */
    private String ingredient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_dishes_entity.style
     *
     * @mbggenerated
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_dishes_entity.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_dishes_entity.id
     *
     * @return the value of shop_dishes_entity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_dishes_entity.id
     *
     * @param id the value for shop_dishes_entity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_dishes_entity.shopname
     *
     * @return the value of shop_dishes_entity.shopname
     *
     * @mbggenerated
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_dishes_entity.shopname
     *
     * @param shopname the value for shop_dishes_entity.shopname
     *
     * @mbggenerated
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_dishes_entity.shopdishes
     *
     * @return the value of shop_dishes_entity.shopdishes
     *
     * @mbggenerated
     */
    public String getShopdishes() {
        return shopdishes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_dishes_entity.shopdishes
     *
     * @param shopdishes the value for shop_dishes_entity.shopdishes
     *
     * @mbggenerated
     */
    public void setShopdishes(String shopdishes) {
        this.shopdishes = shopdishes == null ? null : shopdishes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_dishes_entity.price
     *
     * @return the value of shop_dishes_entity.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_dishes_entity.price
     *
     * @param price the value for shop_dishes_entity.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_dishes_entity.ingredient
     *
     * @return the value of shop_dishes_entity.ingredient
     *
     * @mbggenerated
     */
    public String getIngredient() {
        return ingredient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_dishes_entity.ingredient
     *
     * @param ingredient the value for shop_dishes_entity.ingredient
     *
     * @mbggenerated
     */
    public void setIngredient(String ingredient) {
        this.ingredient = ingredient == null ? null : ingredient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_dishes_entity.style
     *
     * @return the value of shop_dishes_entity.style
     *
     * @mbggenerated
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_dishes_entity.style
     *
     * @param style the value for shop_dishes_entity.style
     *
     * @mbggenerated
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_dishes_entity.count
     *
     * @return the value of shop_dishes_entity.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_dishes_entity.count
     *
     * @param count the value for shop_dishes_entity.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}